package lru

const IN_MEMORY_CACHE_ADD_NEW_KEY = 0
const IN_MEMORY_CACHE_REPLACE_EXISTING_KEY = 1
const IN_MEMORY_CACHE_KEY_INDEX_NOT_FOUND = -1

const EVICTION_MANAGER_KEY_NOT_EXISTS = 0
const EVICTION_MANAGER_KEY_EXISTS = 1
const EVICTION_MANAGER_CACHE_KEY_INDEX_NOT_FOUND = -1
const EVICTION_MANAGER_CACHE_KEY_EMPTY = ""
